version: '3.9'

services:
  app-deploy:
    env_file:
      - aws.env
    image: pennsieve/app-deploy
    volumes:
      - ./terraform:/service/terraform
      # - $HOME/.aws:/root/.aws:ro
    container_name: app-deploy
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /service/main