version: '3.9'

services:
  app-deploy:
    env_file:
      - application.env
    image: pennsieve/app-deploy
    volumes:
      - ./terraform:/service/terraform
      - ./application-deployments:/service/application-deployments
      - $HOME/.aws:/root/.aws:ro
    container_name: app-deploy
    build:
      context: .
      dockerfile: ./Dockerfile_arm64
    entrypoint: /service/main