version: '3.9'

services:
  app-deploy:
    env_file:
      - aws.env
    image: pennsieve/app-deploy
    volumes:
      - ./terraform:/service/terraform
    container_name: app-deploy
    build:
      context: .
      dockerfile: ./Dockerfile_arm64
    entrypoint: /service/main