version: '3.9'

services:
  
  pennsieve-agent:
    env_file:
      - dev.env
    image: pennsieve-agent
    container_name: pennsieve-agent
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: aws-lambda-rie /service/main
    restart: always
    ports:
      - 9000:8080