version: '3.9'

services:
  
  app-wrapper:
    env_file:
      - dev.env
    image: pennsieve/app-wrapper
    volumes:
      - ./data:/service/data
    container_name: app-wrapper
    build:
      context: .
      dockerfile: ./Dockerfile_arm64 # change to Dockerfile on Linux
    entrypoint: /service/main
